# 开启 AOF 持久化（兜底数据安全）
appendonly yes
appendfsync everysec

# 高强度安全拦截
requirepass Wang@123
bind 0.0.0.0
protected-mode yes

# 💡 禁用/重命名高危命令 (防删库跑路、防黑客挖矿)
rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command KEYS ""